POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
    "identifier": "PEPESITO",
    "contrasena": "12345678"
}

### Crear Reserva para el usuario 25
POST http://localhost:3001/api/v1/reservas
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NjQxOTU5MjksImV4cCI6MTc2NDE5OTUyOX0.URlZqeapfcjhwUWc4xwnt-QHBBU55NqZIooDW9Vl9o4yV4lMZpiiAw0euagUEZJnl3SbOSgeNzztKHTmQUxeFQtfSTIYIT3ZzpmxTqmL1rs9qRLztO7eEgsyoiFdJL0gfE1WAA7HWgYW64tU5rwDJitPojNpwQRA8HvAKxX4KUKcYXFYDeTm2Kv2idRl-BmGtTNatEDLmTXWPo7NvzQDpKSGr0HDn6u6-EKPHGPo8haD5E7CNaD9eOvoM0ZHEocI8Xb_fnhMjFG6jzE1YX6O04LIdpMcTdjy09-HV3xXeNqHTv0quduDp53WrRrYMrscASTSii1UMbyrNk4_EZiQzA

{
  "fecha_reserva": "2024-06-15T10:00:00Z",
  "estado_reserva": "ACTIVA",
  "clase_reserva": "SEGUNDACLASE",
  "usuario_id": 25,
  "cantidad_viajeros": 2,
  "trayectoria": "IDAVUELTA",
  "vuelo_ida_id": 29,
  "vuelo_vuelta_id": 30,
  "precio_total": 600000
}


### Crear viajeros
POST http://localhost:3001/api/v1/viajeros
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NjQxOTU5MjksImV4cCI6MTc2NDE5OTUyOX0.URlZqeapfcjhwUWc4xwnt-QHBBU55NqZIooDW9Vl9o4yV4lMZpiiAw0euagUEZJnl3SbOSgeNzztKHTmQUxeFQtfSTIYIT3ZzpmxTqmL1rs9qRLztO7eEgsyoiFdJL0gfE1WAA7HWgYW64tU5rwDJitPojNpwQRA8HvAKxX4KUKcYXFYDeTm2Kv2idRl-BmGtTNatEDLmTXWPo7NvzQDpKSGr0HDn6u6-EKPHGPo8haD5E7CNaD9eOvoM0ZHEocI8Xb_fnhMjFG6jzE1YX6O04LIdpMcTdjy09-HV3xXeNqHTv0quduDp53WrRrYMrscASTSii1UMbyrNk4_EZiQzA

{
  "dni_viajero": "12345678",
  "primer_nombre": "Garzon",
  "primer_apellido": "Vergara",
  "fecha_nacimiento": "1990-05-20",
  "id_genero": 2,
  "telefono": "3001234567",
  "correo_electronico": "b.valencia1@utp.edu.co",
  "nombre_contacto": "Ana Maria",
  "telefono_contacto": "3007654321",
  "usuario_asociado": 25,
  "reserva_id": 1
}

### Crear viajeros
POST http://localhost:3001/api/v1/viajeros
Content-Type: application/json

{
  "dni_viajero": "1234578",
  "primer_nombre": "Ortiz",
  "primer_apellido": "Vergara",
  "fecha_nacimiento": "1990-05-20",
  "id_genero": 2,
  "telefono": "3001234567",
  "correo_electronico": "b.valencia1@utp.edu.co",
  "nombre_contacto": "Ana Maria",
  "telefono_contacto": "3007654321",
  "usuario_asociado": 25,
  "reserva_id": 1
}

### Enviar email de reserva
POST http://localhost:3001/api/v1/reservas/send-confirmation-email
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NjQxODk2OTcsImV4cCI6MTc2NDE5MzI5N30.PGlBeU5VsZ0aezzOaQVN4wBH8QTOE1HSYZmj9Y4qr-N9aGVTD6HwJkMObEyk8AMKuMmw-Fj09uyG9ZBfnFxUAziIrBfM-lzDIwSnSqqQjEZYX3xNbuuv8N99ExdnjETNlkv3wpXGyjbGaeGbT9uUD-9JLxFqyOplUl7UOqL0PLerHZTsdOmJsDYUiOuJL3GGHifNnN3WFkmUoQnyyhT4XwiTmO43xjS4rXlXp4OUz4OuljMK4krLZVQ4SmNKaxou2pd01w_FaojJePo_Bp5GLfpAaRjKP7AAE-K2vJYR8efmtw11xkdoxj9sv2I7Nolv49qOe340FdDz3_lMsZdqIg

{
  "toEmail": "b.valencia1@utp.edu.co",
  "reservaId": 1
}

### Cancelar Reserva
PUT http://localhost:3001/api/v1/reservas/cancel/1
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NjQxOTU5MjksImV4cCI6MTc2NDE5OTUyOX0.URlZqeapfcjhwUWc4xwnt-QHBBU55NqZIooDW9Vl9o4yV4lMZpiiAw0euagUEZJnl3SbOSgeNzztKHTmQUxeFQtfSTIYIT3ZzpmxTqmL1rs9qRLztO7eEgsyoiFdJL0gfE1WAA7HWgYW64tU5rwDJitPojNpwQRA8HvAKxX4KUKcYXFYDeTm2Kv2idRl-BmGtTNatEDLmTXWPo7NvzQDpKSGr0HDn6u6-EKPHGPo8haD5E7CNaD9eOvoM0ZHEocI8Xb_fnhMjFG6jzE1YX6O04LIdpMcTdjy09-HV3xXeNqHTv0quduDp53WrRrYMrscASTSii1UMbyrNk4_EZiQzA

### Obtener vuelo por id 29
GET http://localhost:3001/api/v1/flights/29
Accept: application/json


##cambio de sillas

PATCH http://localhost:3001/api/v1/segmentos-viaje/1/cambiar-asiento
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NjQyMDc1MDQsImV4cCI6MTc2NDIxMTEwNH0.RRK7HRlGEpk-LV8Kh0POPbmOuVKs8mkvZ3PTPFg7B-Mxt2vf0IpPVamsGZicburC_2SF55tglPUyeIZKsDZJ_R5EI1Hf_78f0uDjFZS53iyx3gx5ALDQXOi22aOzSyLNz5z6mEGyO3005Kir_E9cEqwl6JBkOwaBxdXS6eN402B6En_-tMOlnCwJeJN2rebpcq_hflu8AKFnSPJc9KIIYPDR_WJ4_RujnWizz_Px2zNHreNFKX5ILYVwqjhZe--Z2ZcXIvktAfCnI22Hhn0SF6PMsb6HQ_ZS2ranCUnr1vzncoSJwSKsBm5G8kJMO1sNjagDcLlaycfGq-5cduteJQ
{
  "nuevo_asiento_id": 30
}
### ============================================

