### Obtener usuarios

GET http://localhost:3001/api/v1/users/
Accept: application/json

### Crear usuario
POST http://localhost:3001/api/v1/users/register
Content-Type: application/json

{
  "usuario":{
    "descripcion_usuario": "Usuario23",
    "correo_electronico": "nuevo24@usuario.com",
    "contrasena": "1234567",
    "id_rol": 3
  },
    "usuarioPerfil": {
    "dni_usuario": "87654321",
    "primer_nombre": "Maria",
    "segundo_nombre": "Elena",
    "primer_apellido": "Rodriguez",
    "segundo_apellido": "Lopez",
    "fecha_nacimiento": "1985-05-15",
    "pais_nacimiento": "México",
    "estado_nacimiento": "Jalisco",
    "ciudad_nacimiento": "Guadalajara",
    "direccion_facturacion": "Av. Revolución 456, Col. Centro",
    "id_genero_usuario": 2
  }
}

### Crear usuario Admin
POST http://localhost:3001/api/v1/users/crear-admin
Content-Type: application/json

{
  "usuario":{
    "descripcion_usuario": "Usuario Admin",
    "correo_electronico": "admin@usuario.com",
    "contrasena": "123456",
    "id_rol": 2
  }
}