### Obtener usuarios

GET http://localhost:3001/api/v1/users/
Accept: application/json

### Crear usuario
POST http://localhost:3001/api/v1/users/register
Content-Type: application/json

{
  "usuario":{
    "descripcion_usuario": "Usuario",
    "correo_electronico": "nuevo@usuario.com",
    "contrasena": "123456",
    "id_rol": 3
  },
  "usuarioPerfil": {
    "dni_usuario": "12345678",
    "primer_nombre": "Nuevo",
    "segundo_nombre": "",
    "primer_apellido": "Apellido1",
    "segundo_apellido": "Apellido2",
    "fecha_nacimiento": "1990-01-01",
    "lugar_nacimiento": "Ciudad",
    "direccion_facturacion": "Direccion 123",
    "id_genero_usuario": 1
  }
}

### Crear usuario Admin
POST http://localhost:3001/api/v1/users/crear-admin
Content-Type: application/json

{
  "usuario":{
    "descripcion_usuario": "Usuario Admin",
    "correo_electronico": "admin@usuario.com",
    "contrasena": "123456",
    "id_rol": 2
  }
}