### Subir imagen con campos extra
POST http://localhost:3001/api/v1/uploads/profile/create
Content-Type: multipart/form-data; boundary=FormBoundary
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NTk3MTAwMDYsImV4cCI6MTc1OTcxMzYwNn0.AnO3d5bxUmUGWc2Dx5Q3ZM4SqKtjFIl08MAIoNF8GuWvHaTQzwKWxt1499NtHUyMBKFqkbfImz6UIbK4mwgismkp-TSmVr-bZ__6lxfeZ6WvMgK4wzLGNOUVIVAG3GWg8bkyjB-ktMmxYcdPYzzo3XxR2Wr3K3ok3C4E1KoUDgtg2f_wDT9RHRPyPKOXZFXPY0iLhInOl4TIljQKIi3eKWSbN_KnCwcnDrHRYR40I_Gk5ulC_SGdJryZ_6wtsKMlNDXlgDwX5J6lafIV6fUOtE4MLyN7Le6eA52xyN0l5_SFmbS8nsIZ2onL8PJ5OUeo_h25ezZwsGkS14Cnh2vUZg

--FormBoundary
Content-Disposition: form-data; name="imagen"; filename="perfil.jpg"
Content-Type: image/jpeg

< ../../../test_image.png
--FormBoundary--

### Obtener imagen de perfil
GET http://localhost:3001/api/v1/uploads/images/profile/26.jpeg
Accept: image/jpeg
Cookie: access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImRlc2NyaXBjaW9uX3VzdWFyaW8iOiJQRVBFU0lUTyIsImVtYWlsIjoidml5dWVsYUBnbWFpbC5jb20iLCJyb2xlIjozLCJpYXQiOjE3NTk3MTAwMDYsImV4cCI6MTc1OTcxMzYwNn0.AnO3d5bxUmUGWc2Dx5Q3ZM4SqKtjFIl08MAIoNF8GuWvHaTQzwKWxt1499NtHUyMBKFqkbfImz6UIbK4mwgismkp-TSmVr-bZ__6lxfeZ6WvMgK4wzLGNOUVIVAG3GWg8bkyjB-ktMmxYcdPYzzo3XxR2Wr3K3ok3C4E1KoUDgtg2f_wDT9RHRPyPKOXZFXPY0iLhInOl4TIljQKIi3eKWSbN_KnCwcnDrHRYR40I_Gk5ulC_SGdJryZ_6wtsKMlNDXlgDwX5J6lafIV6fUOtE4MLyN7Le6eA52xyN0l5_SFmbS8nsIZ2onL8PJ5OUeo_h25ezZwsGkS14Cnh2vUZg